Update patch set 11
Patch Set 11:

Okay, I believe the current patchset correctly represents the "just run the gerrit ci script" version of this.  It's still failing, so I must be missing something.  Let's just look at the stable-3.1 job for now.  Here's what I see:

0) Here's the bazelisk test command:
https://ci.gerritcodereview.com/t/gerrit/build/ed5683b8d4504b6286f1064b87397449/log/job-output.txt#5399

1) We see: FAILED: //polygerrit-ui/app:template_test_admin (Summary)
https://ci.gerritcodereview.com/t/gerrit/build/ed5683b8d4504b6286f1064b87397449/log/job-output.txt#5467

After a whole lot of text, it ends with:

  Error: Cannot find module 'fried-twinkie'

And that happens for 2 more tests.  I don't understand this at all, and could really use your insight on this.

2) Later, the com.google.gerrit.integration.git.GitProtocolV2IT test fails:
https://ci.gerritcodereview.com/t/gerrit/build/ed5683b8d4504b6286f1064b87397449/log/job-output.txt#14706

That looks like the git version problem that David Ostrovsky pointed out.  Does that mean that the tests require a git version greater than what's in Debian stretch?  That should be easy to solve, either by adding  stretch-backports or moving to buster.

Patch-set: 11